// Code generated by go-swagger; DO NOT EDIT.

package attribute_option

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetAttributesAttributeCodeOptionsReader is a Reader for the GetAttributesAttributeCodeOptions structure.
type GetAttributesAttributeCodeOptionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAttributesAttributeCodeOptionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAttributesAttributeCodeOptionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetAttributesAttributeCodeOptionsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAttributesAttributeCodeOptionsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 406:
		result := NewGetAttributesAttributeCodeOptionsNotAcceptable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAttributesAttributeCodeOptionsOK creates a GetAttributesAttributeCodeOptionsOK with default headers values
func NewGetAttributesAttributeCodeOptionsOK() *GetAttributesAttributeCodeOptionsOK {
	return &GetAttributesAttributeCodeOptionsOK{}
}

/*GetAttributesAttributeCodeOptionsOK handles this case with default header values.

Return attribute options paginated
*/
type GetAttributesAttributeCodeOptionsOK struct {
	Payload *GetAttributesAttributeCodeOptionsOKBody
}

func (o *GetAttributesAttributeCodeOptionsOK) Error() string {
	return fmt.Sprintf("[GET /api/rest/v1/attributes/{attribute_code}/options][%d] getAttributesAttributeCodeOptionsOK  %+v", 200, o.Payload)
}

func (o *GetAttributesAttributeCodeOptionsOK) GetPayload() *GetAttributesAttributeCodeOptionsOKBody {
	return o.Payload
}

func (o *GetAttributesAttributeCodeOptionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetAttributesAttributeCodeOptionsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAttributesAttributeCodeOptionsUnauthorized creates a GetAttributesAttributeCodeOptionsUnauthorized with default headers values
func NewGetAttributesAttributeCodeOptionsUnauthorized() *GetAttributesAttributeCodeOptionsUnauthorized {
	return &GetAttributesAttributeCodeOptionsUnauthorized{}
}

/*GetAttributesAttributeCodeOptionsUnauthorized handles this case with default header values.

Authentication required
*/
type GetAttributesAttributeCodeOptionsUnauthorized struct {
	Payload *GetAttributesAttributeCodeOptionsUnauthorizedBody
}

func (o *GetAttributesAttributeCodeOptionsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/rest/v1/attributes/{attribute_code}/options][%d] getAttributesAttributeCodeOptionsUnauthorized  %+v", 401, o.Payload)
}

func (o *GetAttributesAttributeCodeOptionsUnauthorized) GetPayload() *GetAttributesAttributeCodeOptionsUnauthorizedBody {
	return o.Payload
}

func (o *GetAttributesAttributeCodeOptionsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetAttributesAttributeCodeOptionsUnauthorizedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAttributesAttributeCodeOptionsForbidden creates a GetAttributesAttributeCodeOptionsForbidden with default headers values
func NewGetAttributesAttributeCodeOptionsForbidden() *GetAttributesAttributeCodeOptionsForbidden {
	return &GetAttributesAttributeCodeOptionsForbidden{}
}

/*GetAttributesAttributeCodeOptionsForbidden handles this case with default header values.

Access forbidden
*/
type GetAttributesAttributeCodeOptionsForbidden struct {
	Payload *GetAttributesAttributeCodeOptionsForbiddenBody
}

func (o *GetAttributesAttributeCodeOptionsForbidden) Error() string {
	return fmt.Sprintf("[GET /api/rest/v1/attributes/{attribute_code}/options][%d] getAttributesAttributeCodeOptionsForbidden  %+v", 403, o.Payload)
}

func (o *GetAttributesAttributeCodeOptionsForbidden) GetPayload() *GetAttributesAttributeCodeOptionsForbiddenBody {
	return o.Payload
}

func (o *GetAttributesAttributeCodeOptionsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetAttributesAttributeCodeOptionsForbiddenBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAttributesAttributeCodeOptionsNotAcceptable creates a GetAttributesAttributeCodeOptionsNotAcceptable with default headers values
func NewGetAttributesAttributeCodeOptionsNotAcceptable() *GetAttributesAttributeCodeOptionsNotAcceptable {
	return &GetAttributesAttributeCodeOptionsNotAcceptable{}
}

/*GetAttributesAttributeCodeOptionsNotAcceptable handles this case with default header values.

Not Acceptable
*/
type GetAttributesAttributeCodeOptionsNotAcceptable struct {
	Payload *GetAttributesAttributeCodeOptionsNotAcceptableBody
}

func (o *GetAttributesAttributeCodeOptionsNotAcceptable) Error() string {
	return fmt.Sprintf("[GET /api/rest/v1/attributes/{attribute_code}/options][%d] getAttributesAttributeCodeOptionsNotAcceptable  %+v", 406, o.Payload)
}

func (o *GetAttributesAttributeCodeOptionsNotAcceptable) GetPayload() *GetAttributesAttributeCodeOptionsNotAcceptableBody {
	return o.Payload
}

func (o *GetAttributesAttributeCodeOptionsNotAcceptable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetAttributesAttributeCodeOptionsNotAcceptableBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetAttributesAttributeCodeOptionsForbiddenBody get attributes attribute code options forbidden body
swagger:model GetAttributesAttributeCodeOptionsForbiddenBody
*/
type GetAttributesAttributeCodeOptionsForbiddenBody struct {

	// HTTP status code
	Code int64 `json:"code,omitempty"`

	// Message explaining the error
	Message string `json:"message,omitempty"`
}

// Validate validates this get attributes attribute code options forbidden body
func (o *GetAttributesAttributeCodeOptionsForbiddenBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetAttributesAttributeCodeOptionsForbiddenBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAttributesAttributeCodeOptionsForbiddenBody) UnmarshalBinary(b []byte) error {
	var res GetAttributesAttributeCodeOptionsForbiddenBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetAttributesAttributeCodeOptionsNotAcceptableBody get attributes attribute code options not acceptable body
swagger:model GetAttributesAttributeCodeOptionsNotAcceptableBody
*/
type GetAttributesAttributeCodeOptionsNotAcceptableBody struct {

	// HTTP status code
	Code int64 `json:"code,omitempty"`

	// Message explaining the error
	Message string `json:"message,omitempty"`
}

// Validate validates this get attributes attribute code options not acceptable body
func (o *GetAttributesAttributeCodeOptionsNotAcceptableBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetAttributesAttributeCodeOptionsNotAcceptableBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAttributesAttributeCodeOptionsNotAcceptableBody) UnmarshalBinary(b []byte) error {
	var res GetAttributesAttributeCodeOptionsNotAcceptableBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetAttributesAttributeCodeOptionsOKBody Attribute Options
swagger:model GetAttributesAttributeCodeOptionsOKBody
*/
type GetAttributesAttributeCodeOptionsOKBody struct {

	// links
	Links *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0Links `json:"_links,omitempty"`

	// Current page number
	CurrentPage int64 `json:"current_page,omitempty"`

	// embedded
	Embedded *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1Embedded `json:"_embedded,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *GetAttributesAttributeCodeOptionsOKBody) UnmarshalJSON(raw []byte) error {
	// GetAttributesAttributeCodeOptionsOKBodyAO0
	var dataGetAttributesAttributeCodeOptionsOKBodyAO0 struct {
		Links *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0Links `json:"_links,omitempty"`

		CurrentPage int64 `json:"current_page,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataGetAttributesAttributeCodeOptionsOKBodyAO0); err != nil {
		return err
	}

	o.Links = dataGetAttributesAttributeCodeOptionsOKBodyAO0.Links

	o.CurrentPage = dataGetAttributesAttributeCodeOptionsOKBodyAO0.CurrentPage

	// GetAttributesAttributeCodeOptionsOKBodyAO1
	var dataGetAttributesAttributeCodeOptionsOKBodyAO1 struct {
		Embedded *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1Embedded `json:"_embedded,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataGetAttributesAttributeCodeOptionsOKBodyAO1); err != nil {
		return err
	}

	o.Embedded = dataGetAttributesAttributeCodeOptionsOKBodyAO1.Embedded

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o GetAttributesAttributeCodeOptionsOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	var dataGetAttributesAttributeCodeOptionsOKBodyAO0 struct {
		Links *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0Links `json:"_links,omitempty"`

		CurrentPage int64 `json:"current_page,omitempty"`
	}

	dataGetAttributesAttributeCodeOptionsOKBodyAO0.Links = o.Links

	dataGetAttributesAttributeCodeOptionsOKBodyAO0.CurrentPage = o.CurrentPage

	jsonDataGetAttributesAttributeCodeOptionsOKBodyAO0, errGetAttributesAttributeCodeOptionsOKBodyAO0 := swag.WriteJSON(dataGetAttributesAttributeCodeOptionsOKBodyAO0)
	if errGetAttributesAttributeCodeOptionsOKBodyAO0 != nil {
		return nil, errGetAttributesAttributeCodeOptionsOKBodyAO0
	}
	_parts = append(_parts, jsonDataGetAttributesAttributeCodeOptionsOKBodyAO0)
	var dataGetAttributesAttributeCodeOptionsOKBodyAO1 struct {
		Embedded *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1Embedded `json:"_embedded,omitempty"`
	}

	dataGetAttributesAttributeCodeOptionsOKBodyAO1.Embedded = o.Embedded

	jsonDataGetAttributesAttributeCodeOptionsOKBodyAO1, errGetAttributesAttributeCodeOptionsOKBodyAO1 := swag.WriteJSON(dataGetAttributesAttributeCodeOptionsOKBodyAO1)
	if errGetAttributesAttributeCodeOptionsOKBodyAO1 != nil {
		return nil, errGetAttributesAttributeCodeOptionsOKBodyAO1
	}
	_parts = append(_parts, jsonDataGetAttributesAttributeCodeOptionsOKBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this get attributes attribute code options o k body
func (o *GetAttributesAttributeCodeOptionsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateLinks(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateEmbedded(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetAttributesAttributeCodeOptionsOKBody) validateLinks(formats strfmt.Registry) error {

	if swag.IsZero(o.Links) { // not required
		return nil
	}

	if o.Links != nil {
		if err := o.Links.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getAttributesAttributeCodeOptionsOK" + "." + "_links")
			}
			return err
		}
	}

	return nil
}

func (o *GetAttributesAttributeCodeOptionsOKBody) validateEmbedded(formats strfmt.Registry) error {

	if swag.IsZero(o.Embedded) { // not required
		return nil
	}

	if o.Embedded != nil {
		if err := o.Embedded.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getAttributesAttributeCodeOptionsOK" + "." + "_embedded")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetAttributesAttributeCodeOptionsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAttributesAttributeCodeOptionsOKBody) UnmarshalBinary(b []byte) error {
	var res GetAttributesAttributeCodeOptionsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0Links get attributes attribute code options o k body get attributes attribute code options o k body a o0 links
swagger:model GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0Links
*/
type GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0Links struct {

	// first
	First *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksFirst `json:"first,omitempty"`

	// next
	Next *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksNext `json:"next,omitempty"`

	// previous
	Previous *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksPrevious `json:"previous,omitempty"`

	// self
	Self *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksSelf `json:"self,omitempty"`
}

// Validate validates this get attributes attribute code options o k body get attributes attribute code options o k body a o0 links
func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0Links) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateFirst(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateNext(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validatePrevious(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateSelf(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0Links) validateFirst(formats strfmt.Registry) error {

	if swag.IsZero(o.First) { // not required
		return nil
	}

	if o.First != nil {
		if err := o.First.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getAttributesAttributeCodeOptionsOK" + "." + "_links" + "." + "first")
			}
			return err
		}
	}

	return nil
}

func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0Links) validateNext(formats strfmt.Registry) error {

	if swag.IsZero(o.Next) { // not required
		return nil
	}

	if o.Next != nil {
		if err := o.Next.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getAttributesAttributeCodeOptionsOK" + "." + "_links" + "." + "next")
			}
			return err
		}
	}

	return nil
}

func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0Links) validatePrevious(formats strfmt.Registry) error {

	if swag.IsZero(o.Previous) { // not required
		return nil
	}

	if o.Previous != nil {
		if err := o.Previous.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getAttributesAttributeCodeOptionsOK" + "." + "_links" + "." + "previous")
			}
			return err
		}
	}

	return nil
}

func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0Links) validateSelf(formats strfmt.Registry) error {

	if swag.IsZero(o.Self) { // not required
		return nil
	}

	if o.Self != nil {
		if err := o.Self.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getAttributesAttributeCodeOptionsOK" + "." + "_links" + "." + "self")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0Links) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0Links) UnmarshalBinary(b []byte) error {
	var res GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0Links
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksFirst get attributes attribute code options o k body get attributes attribute code options o k body a o0 links first
swagger:model GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksFirst
*/
type GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksFirst struct {

	// URI of the first page of resources
	Href string `json:"href,omitempty"`
}

// Validate validates this get attributes attribute code options o k body get attributes attribute code options o k body a o0 links first
func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksFirst) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksFirst) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksFirst) UnmarshalBinary(b []byte) error {
	var res GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksFirst
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksNext get attributes attribute code options o k body get attributes attribute code options o k body a o0 links next
swagger:model GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksNext
*/
type GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksNext struct {

	// URI of the next page of resources
	Href string `json:"href,omitempty"`
}

// Validate validates this get attributes attribute code options o k body get attributes attribute code options o k body a o0 links next
func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksNext) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksNext) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksNext) UnmarshalBinary(b []byte) error {
	var res GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksNext
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksPrevious get attributes attribute code options o k body get attributes attribute code options o k body a o0 links previous
swagger:model GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksPrevious
*/
type GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksPrevious struct {

	// URI of the previous page of resources
	Href string `json:"href,omitempty"`
}

// Validate validates this get attributes attribute code options o k body get attributes attribute code options o k body a o0 links previous
func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksPrevious) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksPrevious) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksPrevious) UnmarshalBinary(b []byte) error {
	var res GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksPrevious
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksSelf get attributes attribute code options o k body get attributes attribute code options o k body a o0 links self
swagger:model GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksSelf
*/
type GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksSelf struct {

	// URI of the current page of resources
	Href string `json:"href,omitempty"`
}

// Validate validates this get attributes attribute code options o k body get attributes attribute code options o k body a o0 links self
func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksSelf) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksSelf) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksSelf) UnmarshalBinary(b []byte) error {
	var res GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO0LinksSelf
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1Embedded get attributes attribute code options o k body get attributes attribute code options o k body a o1 embedded
swagger:model GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1Embedded
*/
type GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1Embedded struct {

	// items
	Items []*GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0 `json:"items"`
}

// Validate validates this get attributes attribute code options o k body get attributes attribute code options o k body a o1 embedded
func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1Embedded) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateItems(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1Embedded) validateItems(formats strfmt.Registry) error {

	if swag.IsZero(o.Items) { // not required
		return nil
	}

	for i := 0; i < len(o.Items); i++ {
		if swag.IsZero(o.Items[i]) { // not required
			continue
		}

		if o.Items[i] != nil {
			if err := o.Items[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getAttributesAttributeCodeOptionsOK" + "." + "_embedded" + "." + "items" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1Embedded) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1Embedded) UnmarshalBinary(b []byte) error {
	var res GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1Embedded
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0 get attributes attribute code options o k body get attributes attribute code options o k body a o1 embedded items items0
swagger:model GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0
*/
type GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0 struct {

	// links
	Links *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0AO0Links `json:"_links,omitempty"`

	// Code of attribute related to the attribute option
	Attribute string `json:"attribute,omitempty"`

	// Code of option
	// Required: true
	Code *string `json:"code"`

	// labels
	Labels *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0AO1Labels `json:"labels,omitempty"`

	// Order of attribute option
	SortOrder int64 `json:"sort_order,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		Links *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0AO0Links `json:"_links,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	o.Links = dataAO0.Links

	// AO1
	var dataAO1 struct {
		Attribute string `json:"attribute,omitempty"`

		Code *string `json:"code"`

		Labels *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0AO1Labels `json:"labels,omitempty"`

		SortOrder int64 `json:"sort_order,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	o.Attribute = dataAO1.Attribute

	o.Code = dataAO1.Code

	o.Labels = dataAO1.Labels

	o.SortOrder = dataAO1.SortOrder

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	var dataAO0 struct {
		Links *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0AO0Links `json:"_links,omitempty"`
	}

	dataAO0.Links = o.Links

	jsonDataAO0, errAO0 := swag.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)
	var dataAO1 struct {
		Attribute string `json:"attribute,omitempty"`

		Code *string `json:"code"`

		Labels *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0AO1Labels `json:"labels,omitempty"`

		SortOrder int64 `json:"sort_order,omitempty"`
	}

	dataAO1.Attribute = o.Attribute

	dataAO1.Code = o.Code

	dataAO1.Labels = o.Labels

	dataAO1.SortOrder = o.SortOrder

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this get attributes attribute code options o k body get attributes attribute code options o k body a o1 embedded items items0
func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateLinks(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateCode(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateLabels(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0) validateLinks(formats strfmt.Registry) error {

	if swag.IsZero(o.Links) { // not required
		return nil
	}

	if o.Links != nil {
		if err := o.Links.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("_links")
			}
			return err
		}
	}

	return nil
}

func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0) validateCode(formats strfmt.Registry) error {

	if err := validate.Required("code", "body", o.Code); err != nil {
		return err
	}

	return nil
}

func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0) validateLabels(formats strfmt.Registry) error {

	if swag.IsZero(o.Labels) { // not required
		return nil
	}

	if o.Labels != nil {
		if err := o.Labels.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("labels")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0) UnmarshalBinary(b []byte) error {
	var res GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0AO0Links get attributes attribute code options o k body get attributes attribute code options o k body a o1 embedded items items0 a o0 links
swagger:model GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0AO0Links
*/
type GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0AO0Links struct {

	// self
	Self *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0AO0LinksSelf `json:"self,omitempty"`
}

// Validate validates this get attributes attribute code options o k body get attributes attribute code options o k body a o1 embedded items items0 a o0 links
func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0AO0Links) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateSelf(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0AO0Links) validateSelf(formats strfmt.Registry) error {

	if swag.IsZero(o.Self) { // not required
		return nil
	}

	if o.Self != nil {
		if err := o.Self.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("_links" + "." + "self")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0AO0Links) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0AO0Links) UnmarshalBinary(b []byte) error {
	var res GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0AO0Links
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0AO0LinksSelf get attributes attribute code options o k body get attributes attribute code options o k body a o1 embedded items items0 a o0 links self
swagger:model GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0AO0LinksSelf
*/
type GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0AO0LinksSelf struct {

	// URI of the resource
	Href string `json:"href,omitempty"`
}

// Validate validates this get attributes attribute code options o k body get attributes attribute code options o k body a o1 embedded items items0 a o0 links self
func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0AO0LinksSelf) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0AO0LinksSelf) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0AO0LinksSelf) UnmarshalBinary(b []byte) error {
	var res GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0AO0LinksSelf
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0AO1Labels Attribute option labels for each locale
swagger:model GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0AO1Labels
*/
type GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0AO1Labels struct {

	// Attribute option label for the locale `localeCode`
	LocaleCode string `json:"localeCode,omitempty"`
}

// Validate validates this get attributes attribute code options o k body get attributes attribute code options o k body a o1 embedded items items0 a o1 labels
func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0AO1Labels) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0AO1Labels) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0AO1Labels) UnmarshalBinary(b []byte) error {
	var res GetAttributesAttributeCodeOptionsOKBodyGetAttributesAttributeCodeOptionsOKBodyAO1EmbeddedItemsItems0AO1Labels
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetAttributesAttributeCodeOptionsUnauthorizedBody get attributes attribute code options unauthorized body
swagger:model GetAttributesAttributeCodeOptionsUnauthorizedBody
*/
type GetAttributesAttributeCodeOptionsUnauthorizedBody struct {

	// HTTP status code
	Code int64 `json:"code,omitempty"`

	// Message explaining the error
	Message string `json:"message,omitempty"`
}

// Validate validates this get attributes attribute code options unauthorized body
func (o *GetAttributesAttributeCodeOptionsUnauthorizedBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetAttributesAttributeCodeOptionsUnauthorizedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAttributesAttributeCodeOptionsUnauthorizedBody) UnmarshalBinary(b []byte) error {
	var res GetAttributesAttributeCodeOptionsUnauthorizedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
