// Code generated by go-swagger; DO NOT EDIT.

package reference_entity_record

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPatchReferenceEntityRecordsParams creates a new PatchReferenceEntityRecordsParams object
// with the default values initialized.
func NewPatchReferenceEntityRecordsParams() *PatchReferenceEntityRecordsParams {
	var ()
	return &PatchReferenceEntityRecordsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchReferenceEntityRecordsParamsWithTimeout creates a new PatchReferenceEntityRecordsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchReferenceEntityRecordsParamsWithTimeout(timeout time.Duration) *PatchReferenceEntityRecordsParams {
	var ()
	return &PatchReferenceEntityRecordsParams{

		timeout: timeout,
	}
}

// NewPatchReferenceEntityRecordsParamsWithContext creates a new PatchReferenceEntityRecordsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchReferenceEntityRecordsParamsWithContext(ctx context.Context) *PatchReferenceEntityRecordsParams {
	var ()
	return &PatchReferenceEntityRecordsParams{

		Context: ctx,
	}
}

// NewPatchReferenceEntityRecordsParamsWithHTTPClient creates a new PatchReferenceEntityRecordsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchReferenceEntityRecordsParamsWithHTTPClient(client *http.Client) *PatchReferenceEntityRecordsParams {
	var ()
	return &PatchReferenceEntityRecordsParams{
		HTTPClient: client,
	}
}

/*PatchReferenceEntityRecordsParams contains all the parameters to send to the API endpoint
for the patch reference entity records operation typically these are written to a http.Request
*/
type PatchReferenceEntityRecordsParams struct {

	/*Body*/
	Body []*PatchReferenceEntityRecordsParamsBodyItems0
	/*ReferenceEntityCode
	  Code of the reference entity

	*/
	ReferenceEntityCode string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch reference entity records params
func (o *PatchReferenceEntityRecordsParams) WithTimeout(timeout time.Duration) *PatchReferenceEntityRecordsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch reference entity records params
func (o *PatchReferenceEntityRecordsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch reference entity records params
func (o *PatchReferenceEntityRecordsParams) WithContext(ctx context.Context) *PatchReferenceEntityRecordsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch reference entity records params
func (o *PatchReferenceEntityRecordsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch reference entity records params
func (o *PatchReferenceEntityRecordsParams) WithHTTPClient(client *http.Client) *PatchReferenceEntityRecordsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch reference entity records params
func (o *PatchReferenceEntityRecordsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch reference entity records params
func (o *PatchReferenceEntityRecordsParams) WithBody(body []*PatchReferenceEntityRecordsParamsBodyItems0) *PatchReferenceEntityRecordsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch reference entity records params
func (o *PatchReferenceEntityRecordsParams) SetBody(body []*PatchReferenceEntityRecordsParamsBodyItems0) {
	o.Body = body
}

// WithReferenceEntityCode adds the referenceEntityCode to the patch reference entity records params
func (o *PatchReferenceEntityRecordsParams) WithReferenceEntityCode(referenceEntityCode string) *PatchReferenceEntityRecordsParams {
	o.SetReferenceEntityCode(referenceEntityCode)
	return o
}

// SetReferenceEntityCode adds the referenceEntityCode to the patch reference entity records params
func (o *PatchReferenceEntityRecordsParams) SetReferenceEntityCode(referenceEntityCode string) {
	o.ReferenceEntityCode = referenceEntityCode
}

// WriteToRequest writes these params to a swagger request
func (o *PatchReferenceEntityRecordsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param reference_entity_code
	if err := r.SetPathParam("reference_entity_code", o.ReferenceEntityCode); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
