// Code generated by go-swagger; DO NOT EDIT.

package association_type

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSeveralAssociationTypesPatchParams creates a new SeveralAssociationTypesPatchParams object
// with the default values initialized.
func NewSeveralAssociationTypesPatchParams() *SeveralAssociationTypesPatchParams {
	var ()
	return &SeveralAssociationTypesPatchParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSeveralAssociationTypesPatchParamsWithTimeout creates a new SeveralAssociationTypesPatchParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSeveralAssociationTypesPatchParamsWithTimeout(timeout time.Duration) *SeveralAssociationTypesPatchParams {
	var ()
	return &SeveralAssociationTypesPatchParams{

		timeout: timeout,
	}
}

// NewSeveralAssociationTypesPatchParamsWithContext creates a new SeveralAssociationTypesPatchParams object
// with the default values initialized, and the ability to set a context for a request
func NewSeveralAssociationTypesPatchParamsWithContext(ctx context.Context) *SeveralAssociationTypesPatchParams {
	var ()
	return &SeveralAssociationTypesPatchParams{

		Context: ctx,
	}
}

// NewSeveralAssociationTypesPatchParamsWithHTTPClient creates a new SeveralAssociationTypesPatchParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSeveralAssociationTypesPatchParamsWithHTTPClient(client *http.Client) *SeveralAssociationTypesPatchParams {
	var ()
	return &SeveralAssociationTypesPatchParams{
		HTTPClient: client,
	}
}

/*SeveralAssociationTypesPatchParams contains all the parameters to send to the API endpoint
for the several association types patch operation typically these are written to a http.Request
*/
type SeveralAssociationTypesPatchParams struct {

	/*Body*/
	Body SeveralAssociationTypesPatchBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the several association types patch params
func (o *SeveralAssociationTypesPatchParams) WithTimeout(timeout time.Duration) *SeveralAssociationTypesPatchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the several association types patch params
func (o *SeveralAssociationTypesPatchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the several association types patch params
func (o *SeveralAssociationTypesPatchParams) WithContext(ctx context.Context) *SeveralAssociationTypesPatchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the several association types patch params
func (o *SeveralAssociationTypesPatchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the several association types patch params
func (o *SeveralAssociationTypesPatchParams) WithHTTPClient(client *http.Client) *SeveralAssociationTypesPatchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the several association types patch params
func (o *SeveralAssociationTypesPatchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the several association types patch params
func (o *SeveralAssociationTypesPatchParams) WithBody(body SeveralAssociationTypesPatchBody) *SeveralAssociationTypesPatchParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the several association types patch params
func (o *SeveralAssociationTypesPatchParams) SetBody(body SeveralAssociationTypesPatchBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SeveralAssociationTypesPatchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
