// Code generated by go-swagger; DO NOT EDIT.

package channel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewChannelsPostParams creates a new ChannelsPostParams object
// with the default values initialized.
func NewChannelsPostParams() *ChannelsPostParams {
	var ()
	return &ChannelsPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewChannelsPostParamsWithTimeout creates a new ChannelsPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewChannelsPostParamsWithTimeout(timeout time.Duration) *ChannelsPostParams {
	var ()
	return &ChannelsPostParams{

		timeout: timeout,
	}
}

// NewChannelsPostParamsWithContext creates a new ChannelsPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewChannelsPostParamsWithContext(ctx context.Context) *ChannelsPostParams {
	var ()
	return &ChannelsPostParams{

		Context: ctx,
	}
}

// NewChannelsPostParamsWithHTTPClient creates a new ChannelsPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewChannelsPostParamsWithHTTPClient(client *http.Client) *ChannelsPostParams {
	var ()
	return &ChannelsPostParams{
		HTTPClient: client,
	}
}

/*ChannelsPostParams contains all the parameters to send to the API endpoint
for the channels post operation typically these are written to a http.Request
*/
type ChannelsPostParams struct {

	/*Body*/
	Body ChannelsPostBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the channels post params
func (o *ChannelsPostParams) WithTimeout(timeout time.Duration) *ChannelsPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the channels post params
func (o *ChannelsPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the channels post params
func (o *ChannelsPostParams) WithContext(ctx context.Context) *ChannelsPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the channels post params
func (o *ChannelsPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the channels post params
func (o *ChannelsPostParams) WithHTTPClient(client *http.Client) *ChannelsPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the channels post params
func (o *ChannelsPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the channels post params
func (o *ChannelsPostParams) WithBody(body ChannelsPostBody) *ChannelsPostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the channels post params
func (o *ChannelsPostParams) SetBody(body ChannelsPostBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ChannelsPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
