// Code generated by go-swagger; DO NOT EDIT.

package p_a_m_asset_category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new p a m asset category API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for p a m asset category API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetAssetCategories(params *GetAssetCategoriesParams) (*GetAssetCategoriesOK, error)

	GetAssetCategoriesCode(params *GetAssetCategoriesCodeParams) (*GetAssetCategoriesCodeOK, error)

	PatchAssetCategories(params *PatchAssetCategoriesParams) (*PatchAssetCategoriesOK, error)

	PatchAssetCategoriesCode(params *PatchAssetCategoriesCodeParams) (*PatchAssetCategoriesCodeCreated, *PatchAssetCategoriesCodeNoContent, error)

	PostAssetCategories(params *PostAssetCategoriesParams) (*PostAssetCategoriesCreated, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetAssetCategories gets list of p a m asset categories

  This endpoint allows you to get a list of PAM asset categories. PAM asset categories are paginated and sorted by `root/left`.
*/
func (a *Client) GetAssetCategories(params *GetAssetCategoriesParams) (*GetAssetCategoriesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAssetCategoriesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "get_asset_categories",
		Method:             "GET",
		PathPattern:        "/api/rest/v1/asset-categories",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAssetCategoriesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetAssetCategoriesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for get_asset_categories: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetAssetCategoriesCode gets a p a m asset category

  This endpoint allows you to get the information about a given PAM asset category.
*/
func (a *Client) GetAssetCategoriesCode(params *GetAssetCategoriesCodeParams) (*GetAssetCategoriesCodeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAssetCategoriesCodeParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "get_asset_categories__code_",
		Method:             "GET",
		PathPattern:        "/api/rest/v1/asset-categories/{code}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAssetCategoriesCodeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetAssetCategoriesCodeOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for get_asset_categories__code_: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  PatchAssetCategories updates create several p a m asset categories

  This endpoint allows you to update several PAM asset categories at once.
*/
func (a *Client) PatchAssetCategories(params *PatchAssetCategoriesParams) (*PatchAssetCategoriesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPatchAssetCategoriesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "patch_asset_categories",
		Method:             "PATCH",
		PathPattern:        "/api/rest/v1/asset-categories",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PatchAssetCategoriesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PatchAssetCategoriesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for patch_asset_categories: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  PatchAssetCategoriesCode updates create a p a m asset category

  This endpoint allows you to update a given PAM asset category. Know more about <a href="/documentation/update.html#update-behavior">Update behavior</a>. Note that if no category exists for the given code, it creates it.
*/
func (a *Client) PatchAssetCategoriesCode(params *PatchAssetCategoriesCodeParams) (*PatchAssetCategoriesCodeCreated, *PatchAssetCategoriesCodeNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPatchAssetCategoriesCodeParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "patch_asset_categories__code_",
		Method:             "PATCH",
		PathPattern:        "/api/rest/v1/asset-categories/{code}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PatchAssetCategoriesCodeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, nil, err
	}
	switch value := result.(type) {
	case *PatchAssetCategoriesCodeCreated:
		return value, nil, nil
	case *PatchAssetCategoriesCodeNoContent:
		return nil, value, nil
	}
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for p_a_m_asset_category: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  PostAssetCategories creates a new p a m asset category

  This endpoint allows you to create a new PAM asset category.
*/
func (a *Client) PostAssetCategories(params *PostAssetCategoriesParams) (*PostAssetCategoriesCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostAssetCategoriesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "post_asset_categories",
		Method:             "POST",
		PathPattern:        "/api/rest/v1/asset-categories",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostAssetCategoriesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostAssetCategoriesCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for post_asset_categories: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
