// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPatchCategoriesParams creates a new PatchCategoriesParams object
// with the default values initialized.
func NewPatchCategoriesParams() *PatchCategoriesParams {
	var ()
	return &PatchCategoriesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchCategoriesParamsWithTimeout creates a new PatchCategoriesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchCategoriesParamsWithTimeout(timeout time.Duration) *PatchCategoriesParams {
	var ()
	return &PatchCategoriesParams{

		timeout: timeout,
	}
}

// NewPatchCategoriesParamsWithContext creates a new PatchCategoriesParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchCategoriesParamsWithContext(ctx context.Context) *PatchCategoriesParams {
	var ()
	return &PatchCategoriesParams{

		Context: ctx,
	}
}

// NewPatchCategoriesParamsWithHTTPClient creates a new PatchCategoriesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchCategoriesParamsWithHTTPClient(client *http.Client) *PatchCategoriesParams {
	var ()
	return &PatchCategoriesParams{
		HTTPClient: client,
	}
}

/*PatchCategoriesParams contains all the parameters to send to the API endpoint
for the patch categories operation typically these are written to a http.Request
*/
type PatchCategoriesParams struct {

	/*Body*/
	Body PatchCategoriesBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch categories params
func (o *PatchCategoriesParams) WithTimeout(timeout time.Duration) *PatchCategoriesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch categories params
func (o *PatchCategoriesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch categories params
func (o *PatchCategoriesParams) WithContext(ctx context.Context) *PatchCategoriesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch categories params
func (o *PatchCategoriesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch categories params
func (o *PatchCategoriesParams) WithHTTPClient(client *http.Client) *PatchCategoriesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch categories params
func (o *PatchCategoriesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch categories params
func (o *PatchCategoriesParams) WithBody(body PatchCategoriesBody) *PatchCategoriesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch categories params
func (o *PatchCategoriesParams) SetBody(body PatchCategoriesBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PatchCategoriesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
