// Code generated by go-swagger; DO NOT EDIT.

package reference_entity_attribute

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new reference entity attribute API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for reference entity attribute API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetReferenceEntitiesCodeAttributes(params *GetReferenceEntitiesCodeAttributesParams) (*GetReferenceEntitiesCodeAttributesOK, error)

	GetReferenceEntityAttributesCode(params *GetReferenceEntityAttributesCodeParams) (*GetReferenceEntityAttributesCodeOK, error)

	PatchReferenceEntityAttributesCode(params *PatchReferenceEntityAttributesCodeParams) (*PatchReferenceEntityAttributesCodeCreated, *PatchReferenceEntityAttributesCodeNoContent, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetReferenceEntitiesCodeAttributes gets the list of attributes of a given reference entity

  This endpoint allows you to get the list of attributes of a given reference entity.
*/
func (a *Client) GetReferenceEntitiesCodeAttributes(params *GetReferenceEntitiesCodeAttributesParams) (*GetReferenceEntitiesCodeAttributesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetReferenceEntitiesCodeAttributesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "get_reference_entities__code__attributes",
		Method:             "GET",
		PathPattern:        "/api/rest/v1/reference-entities/{reference_entity_code}/attributes",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetReferenceEntitiesCodeAttributesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetReferenceEntitiesCodeAttributesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for get_reference_entities__code__attributes: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetReferenceEntityAttributesCode gets an attribute of a given reference entity

  This endpoint allows you to get the information about a given attribute for a given reference entity.
*/
func (a *Client) GetReferenceEntityAttributesCode(params *GetReferenceEntityAttributesCodeParams) (*GetReferenceEntityAttributesCodeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetReferenceEntityAttributesCodeParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "get_reference_entity_attributes__code_",
		Method:             "GET",
		PathPattern:        "/api/rest/v1/reference-entities/{reference_entity_code}/attributes/{code}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetReferenceEntityAttributesCodeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetReferenceEntityAttributesCodeOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for get_reference_entity_attributes__code_: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  PatchReferenceEntityAttributesCode updates create an attribute of a given reference entity

  This endpoint allows you to update a given attribute for a given renference entity. Note that if the attribute does not already exist for the given reference entity, it creates it.
*/
func (a *Client) PatchReferenceEntityAttributesCode(params *PatchReferenceEntityAttributesCodeParams) (*PatchReferenceEntityAttributesCodeCreated, *PatchReferenceEntityAttributesCodeNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPatchReferenceEntityAttributesCodeParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "patch_reference_entity_attributes__code_",
		Method:             "PATCH",
		PathPattern:        "/api/rest/v1/reference-entities/{reference_entity_code}/attributes/{code}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PatchReferenceEntityAttributesCodeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, nil, err
	}
	switch value := result.(type) {
	case *PatchReferenceEntityAttributesCodeCreated:
		return value, nil, nil
	case *PatchReferenceEntityAttributesCodeNoContent:
		return nil, value, nil
	}
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for reference_entity_attribute: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
