// Code generated by go-swagger; DO NOT EDIT.

package family

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetFamiliesCodeReader is a Reader for the GetFamiliesCode structure.
type GetFamiliesCodeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetFamiliesCodeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetFamiliesCodeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetFamiliesCodeUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetFamiliesCodeForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetFamiliesCodeNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 406:
		result := NewGetFamiliesCodeNotAcceptable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetFamiliesCodeOK creates a GetFamiliesCodeOK with default headers values
func NewGetFamiliesCodeOK() *GetFamiliesCodeOK {
	return &GetFamiliesCodeOK{}
}

/*GetFamiliesCodeOK handles this case with default header values.

OK
*/
type GetFamiliesCodeOK struct {
	Payload *GetFamiliesCodeOKBody
}

func (o *GetFamiliesCodeOK) Error() string {
	return fmt.Sprintf("[GET /api/rest/v1/families/{code}][%d] getFamiliesCodeOK  %+v", 200, o.Payload)
}

func (o *GetFamiliesCodeOK) GetPayload() *GetFamiliesCodeOKBody {
	return o.Payload
}

func (o *GetFamiliesCodeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetFamiliesCodeOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFamiliesCodeUnauthorized creates a GetFamiliesCodeUnauthorized with default headers values
func NewGetFamiliesCodeUnauthorized() *GetFamiliesCodeUnauthorized {
	return &GetFamiliesCodeUnauthorized{}
}

/*GetFamiliesCodeUnauthorized handles this case with default header values.

Authentication required
*/
type GetFamiliesCodeUnauthorized struct {
	Payload *GetFamiliesCodeUnauthorizedBody
}

func (o *GetFamiliesCodeUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/rest/v1/families/{code}][%d] getFamiliesCodeUnauthorized  %+v", 401, o.Payload)
}

func (o *GetFamiliesCodeUnauthorized) GetPayload() *GetFamiliesCodeUnauthorizedBody {
	return o.Payload
}

func (o *GetFamiliesCodeUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetFamiliesCodeUnauthorizedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFamiliesCodeForbidden creates a GetFamiliesCodeForbidden with default headers values
func NewGetFamiliesCodeForbidden() *GetFamiliesCodeForbidden {
	return &GetFamiliesCodeForbidden{}
}

/*GetFamiliesCodeForbidden handles this case with default header values.

Access forbidden
*/
type GetFamiliesCodeForbidden struct {
	Payload *GetFamiliesCodeForbiddenBody
}

func (o *GetFamiliesCodeForbidden) Error() string {
	return fmt.Sprintf("[GET /api/rest/v1/families/{code}][%d] getFamiliesCodeForbidden  %+v", 403, o.Payload)
}

func (o *GetFamiliesCodeForbidden) GetPayload() *GetFamiliesCodeForbiddenBody {
	return o.Payload
}

func (o *GetFamiliesCodeForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetFamiliesCodeForbiddenBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFamiliesCodeNotFound creates a GetFamiliesCodeNotFound with default headers values
func NewGetFamiliesCodeNotFound() *GetFamiliesCodeNotFound {
	return &GetFamiliesCodeNotFound{}
}

/*GetFamiliesCodeNotFound handles this case with default header values.

Resource not found
*/
type GetFamiliesCodeNotFound struct {
	Payload *GetFamiliesCodeNotFoundBody
}

func (o *GetFamiliesCodeNotFound) Error() string {
	return fmt.Sprintf("[GET /api/rest/v1/families/{code}][%d] getFamiliesCodeNotFound  %+v", 404, o.Payload)
}

func (o *GetFamiliesCodeNotFound) GetPayload() *GetFamiliesCodeNotFoundBody {
	return o.Payload
}

func (o *GetFamiliesCodeNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetFamiliesCodeNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFamiliesCodeNotAcceptable creates a GetFamiliesCodeNotAcceptable with default headers values
func NewGetFamiliesCodeNotAcceptable() *GetFamiliesCodeNotAcceptable {
	return &GetFamiliesCodeNotAcceptable{}
}

/*GetFamiliesCodeNotAcceptable handles this case with default header values.

Not Acceptable
*/
type GetFamiliesCodeNotAcceptable struct {
	Payload *GetFamiliesCodeNotAcceptableBody
}

func (o *GetFamiliesCodeNotAcceptable) Error() string {
	return fmt.Sprintf("[GET /api/rest/v1/families/{code}][%d] getFamiliesCodeNotAcceptable  %+v", 406, o.Payload)
}

func (o *GetFamiliesCodeNotAcceptable) GetPayload() *GetFamiliesCodeNotAcceptableBody {
	return o.Payload
}

func (o *GetFamiliesCodeNotAcceptable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetFamiliesCodeNotAcceptableBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetFamiliesCodeForbiddenBody get families code forbidden body
swagger:model GetFamiliesCodeForbiddenBody
*/
type GetFamiliesCodeForbiddenBody struct {

	// HTTP status code
	Code int64 `json:"code,omitempty"`

	// Message explaining the error
	Message string `json:"message,omitempty"`
}

// Validate validates this get families code forbidden body
func (o *GetFamiliesCodeForbiddenBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetFamiliesCodeForbiddenBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetFamiliesCodeForbiddenBody) UnmarshalBinary(b []byte) error {
	var res GetFamiliesCodeForbiddenBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetFamiliesCodeNotAcceptableBody get families code not acceptable body
swagger:model GetFamiliesCodeNotAcceptableBody
*/
type GetFamiliesCodeNotAcceptableBody struct {

	// HTTP status code
	Code int64 `json:"code,omitempty"`

	// Message explaining the error
	Message string `json:"message,omitempty"`
}

// Validate validates this get families code not acceptable body
func (o *GetFamiliesCodeNotAcceptableBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetFamiliesCodeNotAcceptableBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetFamiliesCodeNotAcceptableBody) UnmarshalBinary(b []byte) error {
	var res GetFamiliesCodeNotAcceptableBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetFamiliesCodeNotFoundBody get families code not found body
swagger:model GetFamiliesCodeNotFoundBody
*/
type GetFamiliesCodeNotFoundBody struct {

	// HTTP status code
	Code int64 `json:"code,omitempty"`

	// Message explaining the error
	Message string `json:"message,omitempty"`
}

// Validate validates this get families code not found body
func (o *GetFamiliesCodeNotFoundBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetFamiliesCodeNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetFamiliesCodeNotFoundBody) UnmarshalBinary(b []byte) error {
	var res GetFamiliesCodeNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetFamiliesCodeOKBody get families code o k body
swagger:model GetFamiliesCodeOKBody
*/
type GetFamiliesCodeOKBody struct {

	// Attribute code used as the main picture in the user interface (only since v2.0)
	AttributeAsImage *string `json:"attribute_as_image,omitempty"`

	// Attribute code used as label
	// Required: true
	AttributeAsLabel *string `json:"attribute_as_label"`

	// attribute requirements
	AttributeRequirements *GetFamiliesCodeOKBodyAttributeRequirements `json:"attribute_requirements,omitempty"`

	// Attributes codes that compose the family
	Attributes []string `json:"attributes"`

	// Family code
	// Required: true
	Code *string `json:"code"`

	// labels
	Labels *GetFamiliesCodeOKBodyLabels `json:"labels,omitempty"`
}

// Validate validates this get families code o k body
func (o *GetFamiliesCodeOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAttributeAsLabel(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateAttributeRequirements(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateCode(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateLabels(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetFamiliesCodeOKBody) validateAttributeAsLabel(formats strfmt.Registry) error {

	if err := validate.Required("getFamiliesCodeOK"+"."+"attribute_as_label", "body", o.AttributeAsLabel); err != nil {
		return err
	}

	return nil
}

func (o *GetFamiliesCodeOKBody) validateAttributeRequirements(formats strfmt.Registry) error {

	if swag.IsZero(o.AttributeRequirements) { // not required
		return nil
	}

	if o.AttributeRequirements != nil {
		if err := o.AttributeRequirements.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getFamiliesCodeOK" + "." + "attribute_requirements")
			}
			return err
		}
	}

	return nil
}

func (o *GetFamiliesCodeOKBody) validateCode(formats strfmt.Registry) error {

	if err := validate.Required("getFamiliesCodeOK"+"."+"code", "body", o.Code); err != nil {
		return err
	}

	return nil
}

func (o *GetFamiliesCodeOKBody) validateLabels(formats strfmt.Registry) error {

	if swag.IsZero(o.Labels) { // not required
		return nil
	}

	if o.Labels != nil {
		if err := o.Labels.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getFamiliesCodeOK" + "." + "labels")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetFamiliesCodeOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetFamiliesCodeOKBody) UnmarshalBinary(b []byte) error {
	var res GetFamiliesCodeOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetFamiliesCodeOKBodyAttributeRequirements Attributes codes of the family that are required for the completeness calculation for each channel
swagger:model GetFamiliesCodeOKBodyAttributeRequirements
*/
type GetFamiliesCodeOKBodyAttributeRequirements struct {

	// channel code
	ChannelCode []string `json:"channelCode"`
}

// Validate validates this get families code o k body attribute requirements
func (o *GetFamiliesCodeOKBodyAttributeRequirements) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetFamiliesCodeOKBodyAttributeRequirements) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetFamiliesCodeOKBodyAttributeRequirements) UnmarshalBinary(b []byte) error {
	var res GetFamiliesCodeOKBodyAttributeRequirements
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetFamiliesCodeOKBodyLabels Family labels for each locale
swagger:model GetFamiliesCodeOKBodyLabels
*/
type GetFamiliesCodeOKBodyLabels struct {

	// Family label for the locale `localeCode`
	LocaleCode string `json:"localeCode,omitempty"`
}

// Validate validates this get families code o k body labels
func (o *GetFamiliesCodeOKBodyLabels) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetFamiliesCodeOKBodyLabels) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetFamiliesCodeOKBodyLabels) UnmarshalBinary(b []byte) error {
	var res GetFamiliesCodeOKBodyLabels
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetFamiliesCodeUnauthorizedBody get families code unauthorized body
swagger:model GetFamiliesCodeUnauthorizedBody
*/
type GetFamiliesCodeUnauthorizedBody struct {

	// HTTP status code
	Code int64 `json:"code,omitempty"`

	// Message explaining the error
	Message string `json:"message,omitempty"`
}

// Validate validates this get families code unauthorized body
func (o *GetFamiliesCodeUnauthorizedBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetFamiliesCodeUnauthorizedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetFamiliesCodeUnauthorizedBody) UnmarshalBinary(b []byte) error {
	var res GetFamiliesCodeUnauthorizedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
