// Code generated by go-swagger; DO NOT EDIT.

package product

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeleteProductsCodeReader is a Reader for the DeleteProductsCode structure.
type DeleteProductsCodeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteProductsCodeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteProductsCodeNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteProductsCodeUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteProductsCodeForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteProductsCodeNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteProductsCodeNoContent creates a DeleteProductsCodeNoContent with default headers values
func NewDeleteProductsCodeNoContent() *DeleteProductsCodeNoContent {
	return &DeleteProductsCodeNoContent{}
}

/*DeleteProductsCodeNoContent handles this case with default header values.

No content to return
*/
type DeleteProductsCodeNoContent struct {
}

func (o *DeleteProductsCodeNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/rest/v1/products/{code}][%d] deleteProductsCodeNoContent ", 204)
}

func (o *DeleteProductsCodeNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteProductsCodeUnauthorized creates a DeleteProductsCodeUnauthorized with default headers values
func NewDeleteProductsCodeUnauthorized() *DeleteProductsCodeUnauthorized {
	return &DeleteProductsCodeUnauthorized{}
}

/*DeleteProductsCodeUnauthorized handles this case with default header values.

Authentication required
*/
type DeleteProductsCodeUnauthorized struct {
	Payload *DeleteProductsCodeUnauthorizedBody
}

func (o *DeleteProductsCodeUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /api/rest/v1/products/{code}][%d] deleteProductsCodeUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteProductsCodeUnauthorized) GetPayload() *DeleteProductsCodeUnauthorizedBody {
	return o.Payload
}

func (o *DeleteProductsCodeUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteProductsCodeUnauthorizedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteProductsCodeForbidden creates a DeleteProductsCodeForbidden with default headers values
func NewDeleteProductsCodeForbidden() *DeleteProductsCodeForbidden {
	return &DeleteProductsCodeForbidden{}
}

/*DeleteProductsCodeForbidden handles this case with default header values.

Access forbidden
*/
type DeleteProductsCodeForbidden struct {
	Payload *DeleteProductsCodeForbiddenBody
}

func (o *DeleteProductsCodeForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api/rest/v1/products/{code}][%d] deleteProductsCodeForbidden  %+v", 403, o.Payload)
}

func (o *DeleteProductsCodeForbidden) GetPayload() *DeleteProductsCodeForbiddenBody {
	return o.Payload
}

func (o *DeleteProductsCodeForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteProductsCodeForbiddenBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteProductsCodeNotFound creates a DeleteProductsCodeNotFound with default headers values
func NewDeleteProductsCodeNotFound() *DeleteProductsCodeNotFound {
	return &DeleteProductsCodeNotFound{}
}

/*DeleteProductsCodeNotFound handles this case with default header values.

Resource not found
*/
type DeleteProductsCodeNotFound struct {
	Payload *DeleteProductsCodeNotFoundBody
}

func (o *DeleteProductsCodeNotFound) Error() string {
	return fmt.Sprintf("[DELETE /api/rest/v1/products/{code}][%d] deleteProductsCodeNotFound  %+v", 404, o.Payload)
}

func (o *DeleteProductsCodeNotFound) GetPayload() *DeleteProductsCodeNotFoundBody {
	return o.Payload
}

func (o *DeleteProductsCodeNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteProductsCodeNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*DeleteProductsCodeForbiddenBody delete products code forbidden body
swagger:model DeleteProductsCodeForbiddenBody
*/
type DeleteProductsCodeForbiddenBody struct {

	// HTTP status code
	Code int64 `json:"code,omitempty"`

	// Message explaining the error
	Message string `json:"message,omitempty"`
}

// Validate validates this delete products code forbidden body
func (o *DeleteProductsCodeForbiddenBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteProductsCodeForbiddenBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteProductsCodeForbiddenBody) UnmarshalBinary(b []byte) error {
	var res DeleteProductsCodeForbiddenBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*DeleteProductsCodeNotFoundBody delete products code not found body
swagger:model DeleteProductsCodeNotFoundBody
*/
type DeleteProductsCodeNotFoundBody struct {

	// HTTP status code
	Code int64 `json:"code,omitempty"`

	// Message explaining the error
	Message string `json:"message,omitempty"`
}

// Validate validates this delete products code not found body
func (o *DeleteProductsCodeNotFoundBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteProductsCodeNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteProductsCodeNotFoundBody) UnmarshalBinary(b []byte) error {
	var res DeleteProductsCodeNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*DeleteProductsCodeUnauthorizedBody delete products code unauthorized body
swagger:model DeleteProductsCodeUnauthorizedBody
*/
type DeleteProductsCodeUnauthorizedBody struct {

	// HTTP status code
	Code int64 `json:"code,omitempty"`

	// Message explaining the error
	Message string `json:"message,omitempty"`
}

// Validate validates this delete products code unauthorized body
func (o *DeleteProductsCodeUnauthorizedBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteProductsCodeUnauthorizedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteProductsCodeUnauthorizedBody) UnmarshalBinary(b []byte) error {
	var res DeleteProductsCodeUnauthorizedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
