// Code generated by go-swagger; DO NOT EDIT.

package product

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostProposalParams creates a new PostProposalParams object
// with the default values initialized.
func NewPostProposalParams() *PostProposalParams {
	var ()
	return &PostProposalParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostProposalParamsWithTimeout creates a new PostProposalParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostProposalParamsWithTimeout(timeout time.Duration) *PostProposalParams {
	var ()
	return &PostProposalParams{

		timeout: timeout,
	}
}

// NewPostProposalParamsWithContext creates a new PostProposalParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostProposalParamsWithContext(ctx context.Context) *PostProposalParams {
	var ()
	return &PostProposalParams{

		Context: ctx,
	}
}

// NewPostProposalParamsWithHTTPClient creates a new PostProposalParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostProposalParamsWithHTTPClient(client *http.Client) *PostProposalParams {
	var ()
	return &PostProposalParams{
		HTTPClient: client,
	}
}

/*PostProposalParams contains all the parameters to send to the API endpoint
for the post proposal operation typically these are written to a http.Request
*/
type PostProposalParams struct {

	/*Code
	  Code of the resource

	*/
	Code string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post proposal params
func (o *PostProposalParams) WithTimeout(timeout time.Duration) *PostProposalParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post proposal params
func (o *PostProposalParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post proposal params
func (o *PostProposalParams) WithContext(ctx context.Context) *PostProposalParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post proposal params
func (o *PostProposalParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post proposal params
func (o *PostProposalParams) WithHTTPClient(client *http.Client) *PostProposalParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post proposal params
func (o *PostProposalParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCode adds the code to the post proposal params
func (o *PostProposalParams) WithCode(code string) *PostProposalParams {
	o.SetCode(code)
	return o
}

// SetCode adds the code to the post proposal params
func (o *PostProposalParams) SetCode(code string) {
	o.Code = code
}

// WriteToRequest writes these params to a swagger request
func (o *PostProposalParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param code
	if err := r.SetPathParam("code", o.Code); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
