// Code generated by go-swagger; DO NOT EDIT.

package product_media_file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetMediaFilesCodeParams creates a new GetMediaFilesCodeParams object
// with the default values initialized.
func NewGetMediaFilesCodeParams() *GetMediaFilesCodeParams {
	var ()
	return &GetMediaFilesCodeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMediaFilesCodeParamsWithTimeout creates a new GetMediaFilesCodeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMediaFilesCodeParamsWithTimeout(timeout time.Duration) *GetMediaFilesCodeParams {
	var ()
	return &GetMediaFilesCodeParams{

		timeout: timeout,
	}
}

// NewGetMediaFilesCodeParamsWithContext creates a new GetMediaFilesCodeParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMediaFilesCodeParamsWithContext(ctx context.Context) *GetMediaFilesCodeParams {
	var ()
	return &GetMediaFilesCodeParams{

		Context: ctx,
	}
}

// NewGetMediaFilesCodeParamsWithHTTPClient creates a new GetMediaFilesCodeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetMediaFilesCodeParamsWithHTTPClient(client *http.Client) *GetMediaFilesCodeParams {
	var ()
	return &GetMediaFilesCodeParams{
		HTTPClient: client,
	}
}

/*GetMediaFilesCodeParams contains all the parameters to send to the API endpoint
for the get media files code operation typically these are written to a http.Request
*/
type GetMediaFilesCodeParams struct {

	/*Code
	  Code of the resource

	*/
	Code string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get media files code params
func (o *GetMediaFilesCodeParams) WithTimeout(timeout time.Duration) *GetMediaFilesCodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get media files code params
func (o *GetMediaFilesCodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get media files code params
func (o *GetMediaFilesCodeParams) WithContext(ctx context.Context) *GetMediaFilesCodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get media files code params
func (o *GetMediaFilesCodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get media files code params
func (o *GetMediaFilesCodeParams) WithHTTPClient(client *http.Client) *GetMediaFilesCodeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get media files code params
func (o *GetMediaFilesCodeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCode adds the code to the get media files code params
func (o *GetMediaFilesCodeParams) WithCode(code string) *GetMediaFilesCodeParams {
	o.SetCode(code)
	return o
}

// SetCode adds the code to the get media files code params
func (o *GetMediaFilesCodeParams) SetCode(code string) {
	o.Code = code
}

// WriteToRequest writes these params to a swagger request
func (o *GetMediaFilesCodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param code
	if err := r.SetPathParam("code", o.Code); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
