// Code generated by go-swagger; DO NOT EDIT.

package attribute_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AttributeGroupsGetListReader is a Reader for the AttributeGroupsGetList structure.
type AttributeGroupsGetListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AttributeGroupsGetListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAttributeGroupsGetListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewAttributeGroupsGetListUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewAttributeGroupsGetListForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 406:
		result := NewAttributeGroupsGetListNotAcceptable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAttributeGroupsGetListOK creates a AttributeGroupsGetListOK with default headers values
func NewAttributeGroupsGetListOK() *AttributeGroupsGetListOK {
	return &AttributeGroupsGetListOK{}
}

/*AttributeGroupsGetListOK handles this case with default header values.

Return attribute groups paginated
*/
type AttributeGroupsGetListOK struct {
	Payload *AttributeGroupsGetListOKBody
}

func (o *AttributeGroupsGetListOK) Error() string {
	return fmt.Sprintf("[GET /api/rest/v1/attribute-groups][%d] attributeGroupsGetListOK  %+v", 200, o.Payload)
}

func (o *AttributeGroupsGetListOK) GetPayload() *AttributeGroupsGetListOKBody {
	return o.Payload
}

func (o *AttributeGroupsGetListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(AttributeGroupsGetListOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAttributeGroupsGetListUnauthorized creates a AttributeGroupsGetListUnauthorized with default headers values
func NewAttributeGroupsGetListUnauthorized() *AttributeGroupsGetListUnauthorized {
	return &AttributeGroupsGetListUnauthorized{}
}

/*AttributeGroupsGetListUnauthorized handles this case with default header values.

Authentication required
*/
type AttributeGroupsGetListUnauthorized struct {
	Payload *AttributeGroupsGetListUnauthorizedBody
}

func (o *AttributeGroupsGetListUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/rest/v1/attribute-groups][%d] attributeGroupsGetListUnauthorized  %+v", 401, o.Payload)
}

func (o *AttributeGroupsGetListUnauthorized) GetPayload() *AttributeGroupsGetListUnauthorizedBody {
	return o.Payload
}

func (o *AttributeGroupsGetListUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(AttributeGroupsGetListUnauthorizedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAttributeGroupsGetListForbidden creates a AttributeGroupsGetListForbidden with default headers values
func NewAttributeGroupsGetListForbidden() *AttributeGroupsGetListForbidden {
	return &AttributeGroupsGetListForbidden{}
}

/*AttributeGroupsGetListForbidden handles this case with default header values.

Access forbidden
*/
type AttributeGroupsGetListForbidden struct {
	Payload *AttributeGroupsGetListForbiddenBody
}

func (o *AttributeGroupsGetListForbidden) Error() string {
	return fmt.Sprintf("[GET /api/rest/v1/attribute-groups][%d] attributeGroupsGetListForbidden  %+v", 403, o.Payload)
}

func (o *AttributeGroupsGetListForbidden) GetPayload() *AttributeGroupsGetListForbiddenBody {
	return o.Payload
}

func (o *AttributeGroupsGetListForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(AttributeGroupsGetListForbiddenBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAttributeGroupsGetListNotAcceptable creates a AttributeGroupsGetListNotAcceptable with default headers values
func NewAttributeGroupsGetListNotAcceptable() *AttributeGroupsGetListNotAcceptable {
	return &AttributeGroupsGetListNotAcceptable{}
}

/*AttributeGroupsGetListNotAcceptable handles this case with default header values.

Not Acceptable
*/
type AttributeGroupsGetListNotAcceptable struct {
	Payload *AttributeGroupsGetListNotAcceptableBody
}

func (o *AttributeGroupsGetListNotAcceptable) Error() string {
	return fmt.Sprintf("[GET /api/rest/v1/attribute-groups][%d] attributeGroupsGetListNotAcceptable  %+v", 406, o.Payload)
}

func (o *AttributeGroupsGetListNotAcceptable) GetPayload() *AttributeGroupsGetListNotAcceptableBody {
	return o.Payload
}

func (o *AttributeGroupsGetListNotAcceptable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(AttributeGroupsGetListNotAcceptableBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*AttributeGroupsGetListForbiddenBody attribute groups get list forbidden body
swagger:model AttributeGroupsGetListForbiddenBody
*/
type AttributeGroupsGetListForbiddenBody struct {

	// HTTP status code
	Code int64 `json:"code,omitempty"`

	// Message explaining the error
	Message string `json:"message,omitempty"`
}

// Validate validates this attribute groups get list forbidden body
func (o *AttributeGroupsGetListForbiddenBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *AttributeGroupsGetListForbiddenBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AttributeGroupsGetListForbiddenBody) UnmarshalBinary(b []byte) error {
	var res AttributeGroupsGetListForbiddenBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*AttributeGroupsGetListNotAcceptableBody attribute groups get list not acceptable body
swagger:model AttributeGroupsGetListNotAcceptableBody
*/
type AttributeGroupsGetListNotAcceptableBody struct {

	// HTTP status code
	Code int64 `json:"code,omitempty"`

	// Message explaining the error
	Message string `json:"message,omitempty"`
}

// Validate validates this attribute groups get list not acceptable body
func (o *AttributeGroupsGetListNotAcceptableBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *AttributeGroupsGetListNotAcceptableBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AttributeGroupsGetListNotAcceptableBody) UnmarshalBinary(b []byte) error {
	var res AttributeGroupsGetListNotAcceptableBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*AttributeGroupsGetListOKBody Attribute groups
swagger:model AttributeGroupsGetListOKBody
*/
type AttributeGroupsGetListOKBody struct {

	// links
	Links *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0Links `json:"_links,omitempty"`

	// Current page number
	CurrentPage int64 `json:"current_page,omitempty"`

	// embedded
	Embedded *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1Embedded `json:"_embedded,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *AttributeGroupsGetListOKBody) UnmarshalJSON(raw []byte) error {
	// AttributeGroupsGetListOKBodyAO0
	var dataAttributeGroupsGetListOKBodyAO0 struct {
		Links *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0Links `json:"_links,omitempty"`

		CurrentPage int64 `json:"current_page,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAttributeGroupsGetListOKBodyAO0); err != nil {
		return err
	}

	o.Links = dataAttributeGroupsGetListOKBodyAO0.Links

	o.CurrentPage = dataAttributeGroupsGetListOKBodyAO0.CurrentPage

	// AttributeGroupsGetListOKBodyAO1
	var dataAttributeGroupsGetListOKBodyAO1 struct {
		Embedded *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1Embedded `json:"_embedded,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAttributeGroupsGetListOKBodyAO1); err != nil {
		return err
	}

	o.Embedded = dataAttributeGroupsGetListOKBodyAO1.Embedded

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o AttributeGroupsGetListOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	var dataAttributeGroupsGetListOKBodyAO0 struct {
		Links *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0Links `json:"_links,omitempty"`

		CurrentPage int64 `json:"current_page,omitempty"`
	}

	dataAttributeGroupsGetListOKBodyAO0.Links = o.Links

	dataAttributeGroupsGetListOKBodyAO0.CurrentPage = o.CurrentPage

	jsonDataAttributeGroupsGetListOKBodyAO0, errAttributeGroupsGetListOKBodyAO0 := swag.WriteJSON(dataAttributeGroupsGetListOKBodyAO0)
	if errAttributeGroupsGetListOKBodyAO0 != nil {
		return nil, errAttributeGroupsGetListOKBodyAO0
	}
	_parts = append(_parts, jsonDataAttributeGroupsGetListOKBodyAO0)
	var dataAttributeGroupsGetListOKBodyAO1 struct {
		Embedded *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1Embedded `json:"_embedded,omitempty"`
	}

	dataAttributeGroupsGetListOKBodyAO1.Embedded = o.Embedded

	jsonDataAttributeGroupsGetListOKBodyAO1, errAttributeGroupsGetListOKBodyAO1 := swag.WriteJSON(dataAttributeGroupsGetListOKBodyAO1)
	if errAttributeGroupsGetListOKBodyAO1 != nil {
		return nil, errAttributeGroupsGetListOKBodyAO1
	}
	_parts = append(_parts, jsonDataAttributeGroupsGetListOKBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this attribute groups get list o k body
func (o *AttributeGroupsGetListOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateLinks(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateEmbedded(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *AttributeGroupsGetListOKBody) validateLinks(formats strfmt.Registry) error {

	if swag.IsZero(o.Links) { // not required
		return nil
	}

	if o.Links != nil {
		if err := o.Links.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("attributeGroupsGetListOK" + "." + "_links")
			}
			return err
		}
	}

	return nil
}

func (o *AttributeGroupsGetListOKBody) validateEmbedded(formats strfmt.Registry) error {

	if swag.IsZero(o.Embedded) { // not required
		return nil
	}

	if o.Embedded != nil {
		if err := o.Embedded.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("attributeGroupsGetListOK" + "." + "_embedded")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *AttributeGroupsGetListOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AttributeGroupsGetListOKBody) UnmarshalBinary(b []byte) error {
	var res AttributeGroupsGetListOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0Links attribute groups get list o k body attribute groups get list o k body a o0 links
swagger:model AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0Links
*/
type AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0Links struct {

	// first
	First *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksFirst `json:"first,omitempty"`

	// next
	Next *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksNext `json:"next,omitempty"`

	// previous
	Previous *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksPrevious `json:"previous,omitempty"`

	// self
	Self *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksSelf `json:"self,omitempty"`
}

// Validate validates this attribute groups get list o k body attribute groups get list o k body a o0 links
func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0Links) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateFirst(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateNext(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validatePrevious(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateSelf(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0Links) validateFirst(formats strfmt.Registry) error {

	if swag.IsZero(o.First) { // not required
		return nil
	}

	if o.First != nil {
		if err := o.First.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("attributeGroupsGetListOK" + "." + "_links" + "." + "first")
			}
			return err
		}
	}

	return nil
}

func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0Links) validateNext(formats strfmt.Registry) error {

	if swag.IsZero(o.Next) { // not required
		return nil
	}

	if o.Next != nil {
		if err := o.Next.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("attributeGroupsGetListOK" + "." + "_links" + "." + "next")
			}
			return err
		}
	}

	return nil
}

func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0Links) validatePrevious(formats strfmt.Registry) error {

	if swag.IsZero(o.Previous) { // not required
		return nil
	}

	if o.Previous != nil {
		if err := o.Previous.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("attributeGroupsGetListOK" + "." + "_links" + "." + "previous")
			}
			return err
		}
	}

	return nil
}

func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0Links) validateSelf(formats strfmt.Registry) error {

	if swag.IsZero(o.Self) { // not required
		return nil
	}

	if o.Self != nil {
		if err := o.Self.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("attributeGroupsGetListOK" + "." + "_links" + "." + "self")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0Links) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0Links) UnmarshalBinary(b []byte) error {
	var res AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0Links
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksFirst attribute groups get list o k body attribute groups get list o k body a o0 links first
swagger:model AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksFirst
*/
type AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksFirst struct {

	// URI of the first page of resources
	Href string `json:"href,omitempty"`
}

// Validate validates this attribute groups get list o k body attribute groups get list o k body a o0 links first
func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksFirst) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksFirst) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksFirst) UnmarshalBinary(b []byte) error {
	var res AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksFirst
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksNext attribute groups get list o k body attribute groups get list o k body a o0 links next
swagger:model AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksNext
*/
type AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksNext struct {

	// URI of the next page of resources
	Href string `json:"href,omitempty"`
}

// Validate validates this attribute groups get list o k body attribute groups get list o k body a o0 links next
func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksNext) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksNext) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksNext) UnmarshalBinary(b []byte) error {
	var res AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksNext
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksPrevious attribute groups get list o k body attribute groups get list o k body a o0 links previous
swagger:model AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksPrevious
*/
type AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksPrevious struct {

	// URI of the previous page of resources
	Href string `json:"href,omitempty"`
}

// Validate validates this attribute groups get list o k body attribute groups get list o k body a o0 links previous
func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksPrevious) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksPrevious) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksPrevious) UnmarshalBinary(b []byte) error {
	var res AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksPrevious
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksSelf attribute groups get list o k body attribute groups get list o k body a o0 links self
swagger:model AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksSelf
*/
type AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksSelf struct {

	// URI of the current page of resources
	Href string `json:"href,omitempty"`
}

// Validate validates this attribute groups get list o k body attribute groups get list o k body a o0 links self
func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksSelf) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksSelf) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksSelf) UnmarshalBinary(b []byte) error {
	var res AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO0LinksSelf
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1Embedded attribute groups get list o k body attribute groups get list o k body a o1 embedded
swagger:model AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1Embedded
*/
type AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1Embedded struct {

	// items
	Items []*AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0 `json:"items"`
}

// Validate validates this attribute groups get list o k body attribute groups get list o k body a o1 embedded
func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1Embedded) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateItems(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1Embedded) validateItems(formats strfmt.Registry) error {

	if swag.IsZero(o.Items) { // not required
		return nil
	}

	for i := 0; i < len(o.Items); i++ {
		if swag.IsZero(o.Items[i]) { // not required
			continue
		}

		if o.Items[i] != nil {
			if err := o.Items[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("attributeGroupsGetListOK" + "." + "_embedded" + "." + "items" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1Embedded) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1Embedded) UnmarshalBinary(b []byte) error {
	var res AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1Embedded
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0 attribute groups get list o k body attribute groups get list o k body a o1 embedded items items0
swagger:model AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0
*/
type AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0 struct {

	// links
	Links *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0AO0Links `json:"_links,omitempty"`

	// Attribute codes that compose the attribute group
	Attributes []string `json:"attributes"`

	// Attribute group code
	// Required: true
	Code *string `json:"code"`

	// labels
	Labels *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0AO1Labels `json:"labels,omitempty"`

	// Attribute group order among other attribute groups
	SortOrder int64 `json:"sort_order,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		Links *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0AO0Links `json:"_links,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	o.Links = dataAO0.Links

	// AO1
	var dataAO1 struct {
		Attributes []string `json:"attributes"`

		Code *string `json:"code"`

		Labels *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0AO1Labels `json:"labels,omitempty"`

		SortOrder int64 `json:"sort_order,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	o.Attributes = dataAO1.Attributes

	o.Code = dataAO1.Code

	o.Labels = dataAO1.Labels

	o.SortOrder = dataAO1.SortOrder

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	var dataAO0 struct {
		Links *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0AO0Links `json:"_links,omitempty"`
	}

	dataAO0.Links = o.Links

	jsonDataAO0, errAO0 := swag.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)
	var dataAO1 struct {
		Attributes []string `json:"attributes"`

		Code *string `json:"code"`

		Labels *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0AO1Labels `json:"labels,omitempty"`

		SortOrder int64 `json:"sort_order,omitempty"`
	}

	dataAO1.Attributes = o.Attributes

	dataAO1.Code = o.Code

	dataAO1.Labels = o.Labels

	dataAO1.SortOrder = o.SortOrder

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this attribute groups get list o k body attribute groups get list o k body a o1 embedded items items0
func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateLinks(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateCode(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateLabels(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0) validateLinks(formats strfmt.Registry) error {

	if swag.IsZero(o.Links) { // not required
		return nil
	}

	if o.Links != nil {
		if err := o.Links.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("_links")
			}
			return err
		}
	}

	return nil
}

func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0) validateCode(formats strfmt.Registry) error {

	if err := validate.Required("code", "body", o.Code); err != nil {
		return err
	}

	return nil
}

func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0) validateLabels(formats strfmt.Registry) error {

	if swag.IsZero(o.Labels) { // not required
		return nil
	}

	if o.Labels != nil {
		if err := o.Labels.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("labels")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0) UnmarshalBinary(b []byte) error {
	var res AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0AO0Links attribute groups get list o k body attribute groups get list o k body a o1 embedded items items0 a o0 links
swagger:model AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0AO0Links
*/
type AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0AO0Links struct {

	// self
	Self *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0AO0LinksSelf `json:"self,omitempty"`
}

// Validate validates this attribute groups get list o k body attribute groups get list o k body a o1 embedded items items0 a o0 links
func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0AO0Links) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateSelf(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0AO0Links) validateSelf(formats strfmt.Registry) error {

	if swag.IsZero(o.Self) { // not required
		return nil
	}

	if o.Self != nil {
		if err := o.Self.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("_links" + "." + "self")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0AO0Links) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0AO0Links) UnmarshalBinary(b []byte) error {
	var res AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0AO0Links
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0AO0LinksSelf attribute groups get list o k body attribute groups get list o k body a o1 embedded items items0 a o0 links self
swagger:model AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0AO0LinksSelf
*/
type AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0AO0LinksSelf struct {

	// URI of the resource
	Href string `json:"href,omitempty"`
}

// Validate validates this attribute groups get list o k body attribute groups get list o k body a o1 embedded items items0 a o0 links self
func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0AO0LinksSelf) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0AO0LinksSelf) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0AO0LinksSelf) UnmarshalBinary(b []byte) error {
	var res AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0AO0LinksSelf
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0AO1Labels Attribute group labels for each locale
swagger:model AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0AO1Labels
*/
type AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0AO1Labels struct {

	// Attribute group label for the locale `localeCode`
	LocaleCode string `json:"localeCode,omitempty"`
}

// Validate validates this attribute groups get list o k body attribute groups get list o k body a o1 embedded items items0 a o1 labels
func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0AO1Labels) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0AO1Labels) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0AO1Labels) UnmarshalBinary(b []byte) error {
	var res AttributeGroupsGetListOKBodyAttributeGroupsGetListOKBodyAO1EmbeddedItemsItems0AO1Labels
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*AttributeGroupsGetListUnauthorizedBody attribute groups get list unauthorized body
swagger:model AttributeGroupsGetListUnauthorizedBody
*/
type AttributeGroupsGetListUnauthorizedBody struct {

	// HTTP status code
	Code int64 `json:"code,omitempty"`

	// Message explaining the error
	Message string `json:"message,omitempty"`
}

// Validate validates this attribute groups get list unauthorized body
func (o *AttributeGroupsGetListUnauthorizedBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *AttributeGroupsGetListUnauthorizedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AttributeGroupsGetListUnauthorizedBody) UnmarshalBinary(b []byte) error {
	var res AttributeGroupsGetListUnauthorizedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
