// Code generated by go-swagger; DO NOT EDIT.

package family_variant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetFamiliesFamilyCodeVariantsCodeReader is a Reader for the GetFamiliesFamilyCodeVariantsCode structure.
type GetFamiliesFamilyCodeVariantsCodeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetFamiliesFamilyCodeVariantsCodeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetFamiliesFamilyCodeVariantsCodeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetFamiliesFamilyCodeVariantsCodeUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetFamiliesFamilyCodeVariantsCodeForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetFamiliesFamilyCodeVariantsCodeNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 406:
		result := NewGetFamiliesFamilyCodeVariantsCodeNotAcceptable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetFamiliesFamilyCodeVariantsCodeOK creates a GetFamiliesFamilyCodeVariantsCodeOK with default headers values
func NewGetFamiliesFamilyCodeVariantsCodeOK() *GetFamiliesFamilyCodeVariantsCodeOK {
	return &GetFamiliesFamilyCodeVariantsCodeOK{}
}

/*GetFamiliesFamilyCodeVariantsCodeOK handles this case with default header values.

OK
*/
type GetFamiliesFamilyCodeVariantsCodeOK struct {
	Payload *GetFamiliesFamilyCodeVariantsCodeOKBody
}

func (o *GetFamiliesFamilyCodeVariantsCodeOK) Error() string {
	return fmt.Sprintf("[GET /api/rest/v1/families/{family_code}/variants/{code}][%d] getFamiliesFamilyCodeVariantsCodeOK  %+v", 200, o.Payload)
}

func (o *GetFamiliesFamilyCodeVariantsCodeOK) GetPayload() *GetFamiliesFamilyCodeVariantsCodeOKBody {
	return o.Payload
}

func (o *GetFamiliesFamilyCodeVariantsCodeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetFamiliesFamilyCodeVariantsCodeOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFamiliesFamilyCodeVariantsCodeUnauthorized creates a GetFamiliesFamilyCodeVariantsCodeUnauthorized with default headers values
func NewGetFamiliesFamilyCodeVariantsCodeUnauthorized() *GetFamiliesFamilyCodeVariantsCodeUnauthorized {
	return &GetFamiliesFamilyCodeVariantsCodeUnauthorized{}
}

/*GetFamiliesFamilyCodeVariantsCodeUnauthorized handles this case with default header values.

Authentication required
*/
type GetFamiliesFamilyCodeVariantsCodeUnauthorized struct {
	Payload *GetFamiliesFamilyCodeVariantsCodeUnauthorizedBody
}

func (o *GetFamiliesFamilyCodeVariantsCodeUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/rest/v1/families/{family_code}/variants/{code}][%d] getFamiliesFamilyCodeVariantsCodeUnauthorized  %+v", 401, o.Payload)
}

func (o *GetFamiliesFamilyCodeVariantsCodeUnauthorized) GetPayload() *GetFamiliesFamilyCodeVariantsCodeUnauthorizedBody {
	return o.Payload
}

func (o *GetFamiliesFamilyCodeVariantsCodeUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetFamiliesFamilyCodeVariantsCodeUnauthorizedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFamiliesFamilyCodeVariantsCodeForbidden creates a GetFamiliesFamilyCodeVariantsCodeForbidden with default headers values
func NewGetFamiliesFamilyCodeVariantsCodeForbidden() *GetFamiliesFamilyCodeVariantsCodeForbidden {
	return &GetFamiliesFamilyCodeVariantsCodeForbidden{}
}

/*GetFamiliesFamilyCodeVariantsCodeForbidden handles this case with default header values.

Access forbidden
*/
type GetFamiliesFamilyCodeVariantsCodeForbidden struct {
	Payload *GetFamiliesFamilyCodeVariantsCodeForbiddenBody
}

func (o *GetFamiliesFamilyCodeVariantsCodeForbidden) Error() string {
	return fmt.Sprintf("[GET /api/rest/v1/families/{family_code}/variants/{code}][%d] getFamiliesFamilyCodeVariantsCodeForbidden  %+v", 403, o.Payload)
}

func (o *GetFamiliesFamilyCodeVariantsCodeForbidden) GetPayload() *GetFamiliesFamilyCodeVariantsCodeForbiddenBody {
	return o.Payload
}

func (o *GetFamiliesFamilyCodeVariantsCodeForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetFamiliesFamilyCodeVariantsCodeForbiddenBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFamiliesFamilyCodeVariantsCodeNotFound creates a GetFamiliesFamilyCodeVariantsCodeNotFound with default headers values
func NewGetFamiliesFamilyCodeVariantsCodeNotFound() *GetFamiliesFamilyCodeVariantsCodeNotFound {
	return &GetFamiliesFamilyCodeVariantsCodeNotFound{}
}

/*GetFamiliesFamilyCodeVariantsCodeNotFound handles this case with default header values.

Resource not found
*/
type GetFamiliesFamilyCodeVariantsCodeNotFound struct {
	Payload *GetFamiliesFamilyCodeVariantsCodeNotFoundBody
}

func (o *GetFamiliesFamilyCodeVariantsCodeNotFound) Error() string {
	return fmt.Sprintf("[GET /api/rest/v1/families/{family_code}/variants/{code}][%d] getFamiliesFamilyCodeVariantsCodeNotFound  %+v", 404, o.Payload)
}

func (o *GetFamiliesFamilyCodeVariantsCodeNotFound) GetPayload() *GetFamiliesFamilyCodeVariantsCodeNotFoundBody {
	return o.Payload
}

func (o *GetFamiliesFamilyCodeVariantsCodeNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetFamiliesFamilyCodeVariantsCodeNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFamiliesFamilyCodeVariantsCodeNotAcceptable creates a GetFamiliesFamilyCodeVariantsCodeNotAcceptable with default headers values
func NewGetFamiliesFamilyCodeVariantsCodeNotAcceptable() *GetFamiliesFamilyCodeVariantsCodeNotAcceptable {
	return &GetFamiliesFamilyCodeVariantsCodeNotAcceptable{}
}

/*GetFamiliesFamilyCodeVariantsCodeNotAcceptable handles this case with default header values.

Not Acceptable
*/
type GetFamiliesFamilyCodeVariantsCodeNotAcceptable struct {
	Payload *GetFamiliesFamilyCodeVariantsCodeNotAcceptableBody
}

func (o *GetFamiliesFamilyCodeVariantsCodeNotAcceptable) Error() string {
	return fmt.Sprintf("[GET /api/rest/v1/families/{family_code}/variants/{code}][%d] getFamiliesFamilyCodeVariantsCodeNotAcceptable  %+v", 406, o.Payload)
}

func (o *GetFamiliesFamilyCodeVariantsCodeNotAcceptable) GetPayload() *GetFamiliesFamilyCodeVariantsCodeNotAcceptableBody {
	return o.Payload
}

func (o *GetFamiliesFamilyCodeVariantsCodeNotAcceptable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetFamiliesFamilyCodeVariantsCodeNotAcceptableBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetFamiliesFamilyCodeVariantsCodeForbiddenBody get families family code variants code forbidden body
swagger:model GetFamiliesFamilyCodeVariantsCodeForbiddenBody
*/
type GetFamiliesFamilyCodeVariantsCodeForbiddenBody struct {

	// HTTP status code
	Code int64 `json:"code,omitempty"`

	// Message explaining the error
	Message string `json:"message,omitempty"`
}

// Validate validates this get families family code variants code forbidden body
func (o *GetFamiliesFamilyCodeVariantsCodeForbiddenBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetFamiliesFamilyCodeVariantsCodeForbiddenBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetFamiliesFamilyCodeVariantsCodeForbiddenBody) UnmarshalBinary(b []byte) error {
	var res GetFamiliesFamilyCodeVariantsCodeForbiddenBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetFamiliesFamilyCodeVariantsCodeNotAcceptableBody get families family code variants code not acceptable body
swagger:model GetFamiliesFamilyCodeVariantsCodeNotAcceptableBody
*/
type GetFamiliesFamilyCodeVariantsCodeNotAcceptableBody struct {

	// HTTP status code
	Code int64 `json:"code,omitempty"`

	// Message explaining the error
	Message string `json:"message,omitempty"`
}

// Validate validates this get families family code variants code not acceptable body
func (o *GetFamiliesFamilyCodeVariantsCodeNotAcceptableBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetFamiliesFamilyCodeVariantsCodeNotAcceptableBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetFamiliesFamilyCodeVariantsCodeNotAcceptableBody) UnmarshalBinary(b []byte) error {
	var res GetFamiliesFamilyCodeVariantsCodeNotAcceptableBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetFamiliesFamilyCodeVariantsCodeNotFoundBody get families family code variants code not found body
swagger:model GetFamiliesFamilyCodeVariantsCodeNotFoundBody
*/
type GetFamiliesFamilyCodeVariantsCodeNotFoundBody struct {

	// HTTP status code
	Code int64 `json:"code,omitempty"`

	// Message explaining the error
	Message string `json:"message,omitempty"`
}

// Validate validates this get families family code variants code not found body
func (o *GetFamiliesFamilyCodeVariantsCodeNotFoundBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetFamiliesFamilyCodeVariantsCodeNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetFamiliesFamilyCodeVariantsCodeNotFoundBody) UnmarshalBinary(b []byte) error {
	var res GetFamiliesFamilyCodeVariantsCodeNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetFamiliesFamilyCodeVariantsCodeOKBody get families family code variants code o k body
swagger:model GetFamiliesFamilyCodeVariantsCodeOKBody
*/
type GetFamiliesFamilyCodeVariantsCodeOKBody struct {

	// Family variant code
	// Required: true
	Code *string `json:"code"`

	// labels
	Labels *GetFamiliesFamilyCodeVariantsCodeOKBodyLabels `json:"labels,omitempty"`

	// Attributes distribution according to the enrichment level
	// Required: true
	VariantAttributeSets []*GetFamiliesFamilyCodeVariantsCodeOKBodyVariantAttributeSetsItems0 `json:"variant_attribute_sets"`
}

// Validate validates this get families family code variants code o k body
func (o *GetFamiliesFamilyCodeVariantsCodeOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCode(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateLabels(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateVariantAttributeSets(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetFamiliesFamilyCodeVariantsCodeOKBody) validateCode(formats strfmt.Registry) error {

	if err := validate.Required("getFamiliesFamilyCodeVariantsCodeOK"+"."+"code", "body", o.Code); err != nil {
		return err
	}

	return nil
}

func (o *GetFamiliesFamilyCodeVariantsCodeOKBody) validateLabels(formats strfmt.Registry) error {

	if swag.IsZero(o.Labels) { // not required
		return nil
	}

	if o.Labels != nil {
		if err := o.Labels.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getFamiliesFamilyCodeVariantsCodeOK" + "." + "labels")
			}
			return err
		}
	}

	return nil
}

func (o *GetFamiliesFamilyCodeVariantsCodeOKBody) validateVariantAttributeSets(formats strfmt.Registry) error {

	if err := validate.Required("getFamiliesFamilyCodeVariantsCodeOK"+"."+"variant_attribute_sets", "body", o.VariantAttributeSets); err != nil {
		return err
	}

	for i := 0; i < len(o.VariantAttributeSets); i++ {
		if swag.IsZero(o.VariantAttributeSets[i]) { // not required
			continue
		}

		if o.VariantAttributeSets[i] != nil {
			if err := o.VariantAttributeSets[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getFamiliesFamilyCodeVariantsCodeOK" + "." + "variant_attribute_sets" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetFamiliesFamilyCodeVariantsCodeOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetFamiliesFamilyCodeVariantsCodeOKBody) UnmarshalBinary(b []byte) error {
	var res GetFamiliesFamilyCodeVariantsCodeOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetFamiliesFamilyCodeVariantsCodeOKBodyLabels Family variant labels for each locale
swagger:model GetFamiliesFamilyCodeVariantsCodeOKBodyLabels
*/
type GetFamiliesFamilyCodeVariantsCodeOKBodyLabels struct {

	// Family variant label for the locale `localeCode`
	LocaleCode string `json:"localeCode,omitempty"`
}

// Validate validates this get families family code variants code o k body labels
func (o *GetFamiliesFamilyCodeVariantsCodeOKBodyLabels) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetFamiliesFamilyCodeVariantsCodeOKBodyLabels) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetFamiliesFamilyCodeVariantsCodeOKBodyLabels) UnmarshalBinary(b []byte) error {
	var res GetFamiliesFamilyCodeVariantsCodeOKBodyLabels
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetFamiliesFamilyCodeVariantsCodeOKBodyVariantAttributeSetsItems0 Enrichment level
swagger:model GetFamiliesFamilyCodeVariantsCodeOKBodyVariantAttributeSetsItems0
*/
type GetFamiliesFamilyCodeVariantsCodeOKBodyVariantAttributeSetsItems0 struct {

	// Codes of attributes bind to this enrichment level
	Attributes []string `json:"attributes"`

	// Codes of attributes used as variant axes
	// Required: true
	Axes []string `json:"axes"`

	// Enrichment level
	// Required: true
	Level *int64 `json:"level"`
}

// Validate validates this get families family code variants code o k body variant attribute sets items0
func (o *GetFamiliesFamilyCodeVariantsCodeOKBodyVariantAttributeSetsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAxes(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateLevel(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetFamiliesFamilyCodeVariantsCodeOKBodyVariantAttributeSetsItems0) validateAxes(formats strfmt.Registry) error {

	if err := validate.Required("axes", "body", o.Axes); err != nil {
		return err
	}

	return nil
}

func (o *GetFamiliesFamilyCodeVariantsCodeOKBodyVariantAttributeSetsItems0) validateLevel(formats strfmt.Registry) error {

	if err := validate.Required("level", "body", o.Level); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetFamiliesFamilyCodeVariantsCodeOKBodyVariantAttributeSetsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetFamiliesFamilyCodeVariantsCodeOKBodyVariantAttributeSetsItems0) UnmarshalBinary(b []byte) error {
	var res GetFamiliesFamilyCodeVariantsCodeOKBodyVariantAttributeSetsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetFamiliesFamilyCodeVariantsCodeUnauthorizedBody get families family code variants code unauthorized body
swagger:model GetFamiliesFamilyCodeVariantsCodeUnauthorizedBody
*/
type GetFamiliesFamilyCodeVariantsCodeUnauthorizedBody struct {

	// HTTP status code
	Code int64 `json:"code,omitempty"`

	// Message explaining the error
	Message string `json:"message,omitempty"`
}

// Validate validates this get families family code variants code unauthorized body
func (o *GetFamiliesFamilyCodeVariantsCodeUnauthorizedBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetFamiliesFamilyCodeVariantsCodeUnauthorizedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetFamiliesFamilyCodeVariantsCodeUnauthorizedBody) UnmarshalBinary(b []byte) error {
	var res GetFamiliesFamilyCodeVariantsCodeUnauthorizedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
